version: "3"
services:
  web:
    container_name: go
    image: redisplayground_web
    tty: true
    volumes:
      - /Users/rchaser53/Desktop/redis-playground:/go/src
    ports:
     - "5000:5000"
    depends_on:
      - redis
    networks:
      - back-tier
    environment:
      - "CLkey=${CL}"
      - "BFkey=${BF}"
      - "BFSecret=${BFSecret}"

  redis:
    container_name: redis
    image: redis
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge