version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - .://Users/rchaser53/Desktop/redis-playground
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"